### ISSUE TITLE
How to change a tab size?

### ISSUE THREAD

**Issue by plugnburn** [dominictarr/hipster#19]
When I press tab, I'd like to have 4-space-sized tabs, not 2 spaces. How to work around this issue?

**Comment by dominictarr** [comment]
ah, that is hardcoded currently. https://github.com/dominictarr/hipster/blob/master/plugins/basics.js#L19

but you only need to change that bit that is `'  '` to something that is set by the config, then you can set that to be 4 in your user config `~/.hipsterrc` or passed via command line.

**Comment by plugnburn** [comment]
So, if I want tabs to be tabs, not spaces, I remove the `.split('\t').join('  ')` snippet from `toLines()` function altogether, right?

P.S. Also, is there any plan to support CoffeeScript syntax highlighting (it's hipster editor, after all :))?

**Comment by plugnburn** [comment]
Nevermind, solved it myself. It's hardcoded in too many places though. Had to modify `plugins/basics.js`, `plugins/control.js`, `plugins/entry.js` and `plugins/indent.js` for everything to work correctly.

**Comment by dominictarr** [comment]
If you want to support a configuration option, I'll merge.
I wrote this in one week, it really needs a rewrite, which I havn't done, though, this is my main editor, still!
